config/routes.rb
Rails.application.routes.draw do

  constraints(:host => /makanio.herokuapp.com/) do
    match "/(*path)" => redirect {|params, req| "https://www.makan.io/#{params[:path]}"},  via: [:get, :post]
  end

  # Temporary
  # if Rails.env.production?
  if true
    root 'prelaunch#index'
  else
    root 'homepage#index'
  end

  # Marketplace
  devise_for :customers, class_name: "Customer::User", path: 'me',
             controllers: { omniauth_callbacks: "customers/omniauth_callbacks" }

  scope module: :marketplace do
    scope '/:city', constraints: {city: /setapak|sungailong/}, as: :city do
      get "/" => "city#show"
      
      resource :cart do
        resources :items, controller: "cart_items"
      end

      resources :menus, only: [:index, :show], path: "foods"
    end
  end

  # Admin Panel
  devise_for :vendor, class_name: "Vendor::User"
  namespace "vendor" do
    get "/" => "main#index", as: :root
    resources :order_chits do
      member { post :reject, :accept, :deliver, :finish }
    end
    resources :subvendors
    resources :subvendors_opening_hours
    resources :subvendors_closing_hours
    resources :food_menus
    resources :food_categories
    resources :food_options do
      resources :choices
    end
    resources :food_allergens
    resources :vendor_users
    resources :areas
  end

  devise_for :subvendor, class_name: "Vendor::Subvendor"
  namespace "subvendor" do
    get "/" => "main#index", as: :root
  end

  if Rails.env.development?
    match "dojo" => "dojo#main", via: [:get, :post]
  end

end

app/models/food/menu.rb
class Food::Menu < ActiveRecord::Base
  acts_as_paranoid
  has_paper_trail ignore: [:availability]
  monetize :base_price_cents
  monetize :subvendor_price_cents

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  
  belongs_to :food_category, class_name: "Food::Category"
  belongs_to :vendor_subvendor, class_name: "Vendor::Subvendor"
  alias_method :subvendor, :vendor_subvendor

  has_many :food_menu_options, class_name: "Food::MenuOption",
           foreign_key: "food_menu_id"
  has_many :food_options, class_name: "Food::Option",
           through: :food_menu_options
  has_many :food_allergy_tags, class_name: "Food::AllergyTag",
           foreign_key: "food_menu_id"
  has_many :food_allergens, through: :food_allergy_tags
  has_many :order_items, as: :orderable

  validates :food_category, presence: true
  validates :vendor_subvendor, presence: true
  validates :title, presence: true
  validates :base_price_cents, presence: true, numericality: true
  validates :code, uniqueness: true, allow_blank: true

  has_attached_file :feature_photo,
                    styles: {
                      medium: "280x210>",
                      thumb: "100x100>"
                    },
                    default_url: "/images/:style/dddddd.png"
                    
  validates_attachment_content_type :feature_photo,
                                    content_type: /\Aimage\/.*\Z/
  
  def to_s
    title
  end

  def available?
    subvendor.open? && availability
  end

  def unavailability_reason
    if availability == false
      return "temporarily unavailable"
    end

    if subvendor.closed?
      return "subvendor #{ subvendor.closure_reason }"
    end
  end

  private

  def slug_candidates
    [
      [:code, :title]
    ]
  end
end

app/controllers/marketplace/cart_items_controller.rb
class Marketplace::CartItemsController < Marketplace::MainController
  def create
    create_order_item
    # params_json
    redirect_to city_cart_path(@city), flash: {success: "#{ @order_item.orderable.title } has been added."}
  end

  private

  def cart_item_params
    params.require(:order_item).permit(
      :food_menu_id,
      :quantity,
      :remarks,
      :extras_attributes => [
        :food_option_choice_id,
        :quantity,
        :id,
        :_destroy
      ]
    )
  end

  def create_order_item
    @order_item = Order::Item.new(cart_item_params)
    @order_chit.items << @order_item
    save_order_chit
  end

end

app/controllers/marketplace/carts_controller.rb
class Marketplace::CartsController < Marketplace::MainController
  def show
    
  end

  def destroy
    reset_cart
    redirect_to city_cart_path(@city), flash: {success: "Cart is cleared!"}
  end

  private

  def reset_cart
    @order_chit.items.clear
  end
end

app/controllers/marketplace/city_controller.rb
class Marketplace::CityController < Marketplace::MainController
  def show
    redirect_to city_menus_path(params[:city])
  end
end

app/controllers/marketplace/main_controller.rb
class Marketplace::MainController < ApplicationController
  layout "marketplace"

  before_action :set_city, :set_vendor, :set_order_chit

  private

  def set_city
    @city = session[:city] = params[:city]
  end

  def set_vendor
    @vendor ||= Vendor::Vendor.find_by(city: @city)
  end

  def set_order_chit
    @order_chit ||= find_order_chit_in_session || build_order_chit
  end

  ##
  # Order chit that is not checked out will be cleared out from database every once in
  # a while. If the order_chit_id in session cannot be found in database, we should set
  # session as nil so a new order chit will be built.

  def find_order_chit_in_session
    if chit_in_session = @vendor.order_chits.find_by_id(session[order_chit_session_key])
      chit_in_session
    else
      session[order_chit_session_key] = nil
    end
  end

  def build_order_chit
    Order::Chit.new(vendor_vendor: @vendor, status: :draft)
  end

  def save_order_chit
    @order_chit.save! and session[order_chit_session_key] = @order_chit.id
  end

  def order_chit_session_key
    "chit_for_#{ set_vendor.id }"
  end

  def raise_not_found(e)
    render template: "layouts/marketplace/not_found", status: 404
    raise if Rails.env.development?
  end

end

app/controllers/marketplace/menus_controller.rb
class Marketplace::MenusController < Marketplace::MainController
  before_action :filter_food_menus, only: [:index]
  before_action :set_menu, :build_order_item, only: [:show]

  helper_method :extra_form_for

  def index
    @title = "Setapak Food Delivery by Running Man"
  end

  def show
    @title = "#{ @menu } Delivery in Setapak"
  end

  private

  def set_vendor
    @vendor = Vendor::Vendor.find_by(city: params[:city])
  end

  def filter_food_menus
    set_vendor
    @categories = @vendor.food_categories.includes(:food_menus)
    # @menus = @vendor.food_menus
  end

  def set_menu
    set_vendor

    begin
      @vendor = Vendor::Vendor.find_by(city: params[:city])
      @menu = @vendor.food_menus.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      raise_not_found(e)
    end
  end

  def build_order_item
    @order_item = Order::Item.new(orderable: @menu)
  end

  def extra_form_for(food_option)
    "marketplace/menus/extra_forms/" + food_option.kind
  end
end

app/views/marketplace/menus/_menu_card.html.slim
li
  .menu-card: .row
    .menu-image.small-4.medium-12.columns
      = image_tag menu.feature_photo.url(:medium)
    .small-8.medium-12.columns
      h5.menu-title = menu
      .row
        .small-6.columns: .menu-base-price 
          = humanized_money_with_symbol menu.base_price
        .small-6.columns
          / TODO: To handle food menu unavailable and shit
          = link_to "Order", city_menu_path(params[:city], menu), class: "button tiny expand success"

app/views/marketplace/menus/_menus_per_category.html.slim
a[name="#{ category.to_s.gsub(/ /, '').underscore }"]
.row
  h3 = category
  
  ul.menu-block-grid
    - category.food_menus.each do |menu|
      == render "menu_card", menu: menu
      / li = link_to menu.title, city_menu_path(params[:city], menu)

app/views/marketplace/menus/_show_form.html.slim
#visible-food-option-form
  - @menu.food_options.each do |food_option|
    = render extra_form_for(food_option), food_option: food_option

= simple_form_for @order_item, url: city_cart_items_path do |f|
  = f.hidden_field :food_menu_id
  
  - @menu.food_options.each do |food_option|
    .hidden-food-option-form-field[
      id="hidden_form_field_#{ food_option.id }"
      data-food-option-id=food_option.id
    ]

  = f.submit "Add to Cart", class: "button success"

app/views/marketplace/menus/index.html.slim
.row
  .show-for-medium-up.small-12.medium-2.columns.categories-index
    ul.side-nav
      - @categories.each do |category|
        li = link_to category, "##{ category.to_s.gsub(/ /, '').underscore }"

  .small-12.medium-9.columns
    - @categories.each do |category|
      == render "menus_per_category", category: category

app/views/marketplace/menus/show.html.slim
.row
  / Food Main Column
  .small-12.large-9.columns
    .row
      .small-12.medium-3.columns
        = image_tag @menu.feature_photo.url(:medium)
      .small-12.medium-9.columns
        h3 = @menu.title
        p = humanized_money_with_symbol @menu.base_price
    .row
      == render "show_form", menu: @menu

  .show-for-medium-up.large-3.columns
    panel
      h4 Cart

/ mobile: cart info fixed to screen bottom
.show-for-small-only

/ == javascript_include_tag "marketplace/menus_show"